acce-better-edu/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'dashboard#index'

  get 'dashboard/', to: 'dashboard#index'

  #Ruta para los formularios de la aplicación web
  resources :departamento

  resources :ciudad

  resources :universidad

  resources :rol

  resources :tipodocumento

  resources :persona

  #Ruta para api rest

  namespace :api do
    namespace :v1 do
      resources :departamento
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

acce-better-edu/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

acce-better-edu/app/models/ciudad.rb
class Ciudad < ApplicationRecord

  #Una Ciudad pertenece a un departamento
  belongs_to :departamento

  #Una Ciudad tiene muchas Universidades
  has_many :universidad

end

acce-better-edu/app/models/convocatorium.rb
class Convocatorium < ApplicationRecord

    belongs_to :programa
end

acce-better-edu/app/models/departamento.rb
class Departamento < ApplicationRecord

  #Un Departamento tiene muchas Ciudades o Municipios
  has_many :ciudad

end

acce-better-edu/app/models/permiso.rb
class Permiso < ApplicationRecord

    belongs_to :rol
end

acce-better-edu/app/models/persona.rb
class Persona < ApplicationRecord

    belongs_to :tipo_documento

    has_many :user

    has_many :persona_universidad
    has_many :universidad, through: :persona_universidad
end

acce-better-edu/app/models/persona_universidad.rb
class PersonaUniversidad < ApplicationRecord
end

acce-better-edu/app/models/programa.rb
class Programa < ApplicationRecord

    belongs_to :universidad

    has_many :convocatorium
end

acce-better-edu/app/models/rol.rb
class Rol < ApplicationRecord

    has_many :permiso
    has_many :user
end

acce-better-edu/app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord

    has_many :persona
end

acce-better-edu/app/models/universidad.rb
class Universidad < ApplicationRecord

  #Una Universidad pertenece a una Ciudad
  belongs_to :ciudad

  #Una Universidad tiene muchos programas
  has_many :programa

  has_many :persona_universidad
  has_many :persona, through: :persona_universidad

end

acce-better-edu/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :rol
  belongs_to :persona
end

acce-better-edu/app/controllers/rol_controller.rb
class RolController < ApplicationController

  before_action :authenticate_user!
  before_action :set_rol, only: [:edit, :update]

  def index
    @roles = Rol.all
  end

  def new
  end

  def create

    validar = Rol.find_by(nombre: request_params[:nombre])

    if validar.nil?

      rol = Rol.new(request_params)

      response = rol.save

      if response

        render json: {
            estado: 0,
            mensaje: "Success: El Rol fue creado correctamente"
        }
      else

        render json: {
            estado: 1,
            mensaje: "Error: No se pudo crear el rol"
        }
      end

    else
      render json: {
          estado: 1,
          mensaje: "Error: El rol ya existe descripción: " + validar.descripcion
      }
    end

  end

  def edit
  end

  def update

    response = @rol.update(request_params);

    if response

      render json: {
          estado: 0,
          mensaje: "Success: El rol fue actualizado correctamente"
      }
    else

      render json: {
          estado: 1,
          mensaje: "Error: No se pudo actualizar el rol"
      }
    end

  end

  private

  def set_rol
    @rol = Rol.find(params[:id])
  end

  def request_params
    params.require(:rol).permit(
        :nombre,
        :menu,
        :descripcion
    )
  end
end

acce-better-edu/app/helpers/application_helper.rb
module ApplicationHelper
end

acce-better-edu/app/helpers/ciudad_helper.rb
module CiudadHelper
end

acce-better-edu/app/helpers/convocatoria_helper.rb
module ConvocatoriaHelper
end

acce-better-edu/app/helpers/dashboard_helper.rb
module DashboardHelper
end

acce-better-edu/app/helpers/departamento_helper.rb
module DepartamentoHelper
end

acce-better-edu/app/helpers/permiso_helper.rb
module PermisoHelper
end

acce-better-edu/app/helpers/persona_helper.rb
module PersonaHelper
end

acce-better-edu/app/helpers/programa_helper.rb
module ProgramaHelper
end

acce-better-edu/app/helpers/rol_helper.rb
module RolHelper
end

acce-better-edu/app/helpers/universidad_helper.rb
module UniversidadHelper
end

acce-better-edu/app/views/rol/edit.html.erb
<div class="center">
  <h4>Actualizar Rol</h4>
</div>
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div id="div-message" class="hidden-element">
      <span id="span-message" class="white-text"></span>
    </div>
    <div id="div-progress" class="progress hidden-element">
      <div class="indeterminate"></div>
    </div>
  </div>
</div>
<div class="row">
  <form id="frm-modificarRol" class="col s12 m6 offset-m3">
    <div class="row">
      <div class="input-field col s12">
        <input id="txt-nombre" type="text" name="txt-nombre" class="validate" maxlength="3" value="<%= @rol.nombre %>">
        <label for="txt-nombre">Nombre *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-menu" type="text" name="txt-menu" class="validate" maxlength="3" value="<%= @rol.menu %>">
        <label for="txt-menu">Menu *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-descripcion" type="text" name="txt-descripcion" class="validate" value="<%= @rol.descripcion %>">
        <label for="txt-descripcion">Descripcion *</label>
      </div>
    </div>
    <div class="row">
      <div class="col s6">
        <input type="hidden" name="txt-id" value="<%= @rol.id %>">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button type="button" class="btn" id="btn-modificarRol" onclick="">
          Actualizar <i class="material-icons right">edit</i>
        </button>
      </div>
      <div class="col s6">
        <a href="<%= rol_index_path %>" class="btn">
          Listar <i class="material-icons right">list</i>
        </a>
      </div>
    </div>
  </form>
</div>

acce-better-edu/app/views/rol/index.html.erb
<div class="row">
  <div class="col s12 center">
    <h2>Roles</h2>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <table class="highlight responsive-table">
      <thead>
      <tr>
        <th>Nombre</th>
        <th>Menu Actual</th>
        <th>Descripciòn</th>
        <th>Editar</th>
      </tr>
      </thead>
      <tbody>
      <% @roles.each do |rol| %>
        <tr>
          <td><%= rol.nombre %></td>
          <td><%= rol.menu%></td>
          <td><%= rol.descripcion %></td>
          <td>
            <a href="<%= edit_rol_path(rol.id) %>"><i class="material-icons">edit</i></a>
          </td>
        </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

acce-better-edu/app/views/rol/new.html.erb
<div class="center">
  <h4>Crear Rol</h4>
</div>
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div id="div-message" class="hidden-element">
      <span id="span-message" class="white-text"></span>
    </div>
    <div id="div-progress" class="progress hidden-element">
      <div class="indeterminate"></div>
    </div>
  </div>
</div>
<div class="row">
  <form id="frm-crearRol" class="col s12 m6 offset-m3">
    <div class="row">
      <div class="input-field col s12">
        <input id="txt-nombre" type="text" name="txt-nombre" class="validate">
        <label for="txt-nombre">Nombre *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-menu" type="text" name="txt-menu" class="validate">
        <label for="txt-menu">Menu *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-descripcion" type="text" name="txt-descripcion" class="validate">
        <label for="txt-descripcion">Descripcion *</label>
      </div>
    </div>
    <div class="row">
      <div class="col s6">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button type="button" class="btn" id="btn-crearRol" onclick="">
          Crear <i class="material-icons right">save</i>
        </button>
      </div>
      <div class="col s6">
        <a href="<%= rol_index_path %>" class="btn">
          Listar <i class="material-icons right">list</i>
        </a>
      </div>
    </div>
  </form>
</div>