acce-better-edu/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'dashboard#index'

  get 'dashboard/', to: 'dashboard#index'

  #Ruta para los formularios de la aplicación web
  resources :departamento

  resources :ciudad

  resources :universidad

  resources :rol

  resources :tipodocumento

  resources :persona

  #Ruta para api rest

  namespace :api do
    namespace :v1 do
      resources :departamento
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

acce-better-edu/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

acce-better-edu/app/models/ciudad.rb
class Ciudad < ApplicationRecord

  #Una Ciudad pertenece a un departamento
  belongs_to :departamento

  #Una Ciudad tiene muchas Universidades
  has_many :universidad

end

acce-better-edu/app/models/convocatorium.rb
class Convocatorium < ApplicationRecord

    belongs_to :programa
end

acce-better-edu/app/models/departamento.rb
class Departamento < ApplicationRecord

  #Un Departamento tiene muchas Ciudades o Municipios
  has_many :ciudad

end

acce-better-edu/app/models/permiso.rb
class Permiso < ApplicationRecord

    belongs_to :rol
end

acce-better-edu/app/models/persona.rb
class Persona < ApplicationRecord

    belongs_to :tipo_documento

    has_many :user

    has_many :persona_universidad
    has_many :universidad, through: :persona_universidad
end

acce-better-edu/app/models/programa.rb
class Programa < ApplicationRecord

    belongs_to :universidad

    has_many :convocatorium
end

acce-better-edu/app/models/rol.rb
class Rol < ApplicationRecord

    has_many :permiso
    has_many :user
end

acce-better-edu/app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord

    has_many :persona
end

acce-better-edu/app/models/universidad.rb
class Universidad < ApplicationRecord

  #Una Universidad pertenece a una Ciudad
  belongs_to :ciudad

  #Una Universidad tiene muchos programas
  has_many :programa

  has_many :persona_universidad
  has_many :persona, through: :persona_universidad

end

acce-better-edu/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :rol
  belongs_to :persona
end

acce-better-edu/app/controllers/rol_controller.rb
class RolController < ApplicationController

  before_action :authenticate_user!
  before_action :set_rol, only: [:edit, :update]

  def index
    @roles = Rol.all
  end

  def new
  end

  def create

    validar = Rol.find_by(nombre: request_params[:nombre])

    if validar.nil?

      rol = Rol.new(request_params)

      response = rol.save

      if response

        render json: {
            estado: 0,
            mensaje: "Success: El Rol fue creado correctamente"
        }
      else

        render json: {
            estado: 1,
            mensaje: "Error: No se pudo crear el rol"
        }
      end

    else
      render json: {
          estado: 1,
          mensaje: "Error: El rol ya existe descripción: " + validar.descripcion
      }
    end

  end

  def edit
  end

  def update

    response = @rol.update(request_params);

    if response

      render json: {
          estado: 0,
          mensaje: "Success: El rol fue actualizado correctamente"
      }
    else

      render json: {
          estado: 1,
          mensaje: "Error: No se pudo actualizar el rol"
      }
    end

  end

  private

  def set_rol
    @rol = Rol.find(params[:id])
  end

  def request_params
    params.require(:rol).permit(
        :nombre,
        :menu,
        :descripcion
    )
  end
end

acce-better-edu/app/helpers/application_helper.rb
module ApplicationHelper
end

acce-better-edu/app/helpers/ciudad_helper.rb
module CiudadHelper
end

acce-better-edu/app/helpers/dashboard_helper.rb
module DashboardHelper
end

acce-better-edu/app/helpers/permiso_helper.rb
module PermisoHelper
end

acce-better-edu/app/helpers/persona_helper.rb
module PersonaHelper
end

acce-better-edu/app/helpers/programa_helper.rb
module ProgramaHelper
end

acce-better-edu/app/helpers/rol_helper.rb
module RolHelper
end

acce-better-edu/app/helpers/universidad_helper.rb
module UniversidadHelper
end

acce-better-edu/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>AccessBetterEducation</title>

  <meta name="viewport" content="width=device-width, initial-scale=1.0"/>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/css/materialize.min.css">

  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>

<% if user_signed_in? %>
  <%= render partial: current_user.rol.menu %>

  <div class="row">
    <div class="col s12 m9 offset-m3">

      <%= yield %>

      <div class="row">
        <div class="col 12 m6">
          <% if notice && user_signed_in? %>
            <div class="card-panel teal lighten-2">
          <span id="span-message" class="white-text">
            <%= notice %>
          </span>
            </div>
          <% end %>

          <% if alert %>
            <div class="card-panel red lighten-2">
          <span id="span-message" class="white-text">
            <%= alert %>
          </span>
            </div>
          <% end %>
        </div>
      </div>
    </div>
  </div>

<% else %>
  <%= render partial: 'shared/navbar_login.html.erb' %>

  <%= yield %>

  <% if notice && user_signed_in? %>
    <div class="row">
      <div class="col s12 m9 offset-m3">
        <div class="row">
          <div class="col 12 m6">
            <div class="card-panel teal lighten-2">
              <span id="span-message" class="white-text">
                <%= notice %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>

  <% if alert %>
    <div class="row">
      <div class="col s12 m9 offset-m3">
        <div class="row">
          <div class="col 12 m6">
            <div class="card-panel red lighten-2">
              <span id="span-message" class="white-text">
                <%= alert %>
              </span>
            </div>
          </div>
        </div>
      </div>
    </div>
  <% end %>
<% end %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0-rc.2/js/materialize.min.js"></script>
<script>
    $(document).ready(function () {
        materializeInit();
    });
</script>
</body>
</html>

acce-better-edu/app/views/shared/_navbar_admin_abe.html.erb
<header>
  <div class="navbar-fixed">
    <nav class="">
      <div class="container nav-wrapper">
        <a href="<%= root_path %>" id="logo-st" class="brand-logo center">Access Better Education</a>
        <a href="<%= root_path %>" id="logo-nd" class="brand-logo center">ABE</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <a rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="material-icons left">exit_to_app</i> Logout
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
  <div>
    <ul class="sidenav sidenav-fixed" id="mobile-demo">
      <li>
        <div class="user-view">
          <div class="background">
            <img src="https://materializecss.com/images/office.jpg">
          </div>
          <a href="#user"><img class="circle" src="https://materializecss.com/images/yuna.jpg"></a>
          <a href="#name"><span class="white-text name">Admin Plataforma</span></a>
          <a href="#email">
            <span class="white-text email">
              <%= current_user.email %>
            </span>
          </a>
        </div>
      </li>
      <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
          <!-- Departamento -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" tabindex="0">
              <i class="material-icons no-padding">folder_open</i> Departamento
            </a>
            <div class="collapsible-body">
              <ul>
                <li>
                  <a href="<%= new_departamento_path %>">
                    <i class="material-icons no-padding">save</i>Crear
                  </a>
                </li>
                <li>
                  <a href="<%= departamento_index_path %>">
                    <i class="material-icons no-padding">list</i>Listar
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <!-- Ciudad -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" tabindex="0">
              <i class="material-icons no-padding">folder_open</i> Ciudad
            </a>
            <div class="collapsible-body">
              <ul>
                <li>
                  <a href="<%= new_ciudad_path %>">
                    <i class="material-icons no-padding">save</i>Crear
                  </a>
                </li>
                <li>
                  <a href="<%= ciudad_index_path %>">
                    <i class="material-icons no-padding">list</i>Listar
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <!-- Universidad -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" tabindex="0">
              <i class="material-icons no-padding">folder_open</i> Universidad
            </a>
            <div class="collapsible-body">
              <ul>
                <li>
                  <a href="<%= new_universidad_path %>">
                    <i class="material-icons no-padding">save</i>Crear
                  </a>
                </li>
                <li>
                  <a href="<%= universidad_index_path %>">
                    <i class="material-icons no-padding">list</i>Listar
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <!-- Rol -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" tabindex="0">
              <i class="material-icons no-padding">folder_open</i> Rol
            </a>
            <div class="collapsible-body">
              <ul>
                <li>
                  <a href="<%= new_rol_path %>">
                    <i class="material-icons no-padding">save</i>Crear
                  </a>
                </li>
                <li>
                  <a href="<%= rol_index_path %>">
                    <i class="material-icons no-padding">list</i>Listar
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <!-- Tipo Documento -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" tabindex="0">
              <i class="material-icons no-padding">folder_open</i> Tipo Documento
            </a>
            <div class="collapsible-body">
              <ul>
                <li>
                  <a href="<%= new_tipodocumento_path %>">
                    <i class="material-icons no-padding">save</i>Crear
                  </a>
                </li>
                <li>
                  <a href="<%= tipodocumento_index_path %>">
                    <i class="material-icons no-padding">list</i>Listar
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <!-- Persona -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" tabindex="0">
              <i class="material-icons no-padding">folder_open</i> Persona
            </a>
            <div class="collapsible-body">
              <ul>
                <li>
                  <a href="<%= new_persona_path %>">
                    <i class="material-icons no-padding">person_add</i>Crear
                  </a>
                </li>
                <li>
                  <a href="<%= persona_index_path %>">
                    <i class="material-icons no-padding">list</i>Listar
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="material-icons">group_work</i>Asociar Rol
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <!-- Log out -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="material-icons">exit_to_app</i> Logout
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</header>

acce-better-edu/app/views/shared/_navbar_admin_universidad.erb
<header>
  <div class="navbar-fixed">
    <nav class="">
      <div class="container nav-wrapper">
        <a href="<%= root_path %>" id="logo-st" class="brand-logo center">Access Better Education</a>
        <a href="<%= root_path %>" id="logo-nd" class="brand-logo center">ABE</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <a rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="material-icons left">exit_to_app</i> Logout
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
  <div>
    <ul class="sidenav sidenav-fixed" id="mobile-demo">
      <li>
        <div class="user-view">
          <div class="background">
            <img src="https://materializecss.com/images/office.jpg">
          </div>
          <a href="#user"><img class="circle" src="https://materializecss.com/images/yuna.jpg"></a>
          <a href="#name"><span class="white-text name">Admin Universidad</span></a>
          <a href="#email">
            <span class="white-text email">
              <%= current_user.email %>
            </span>
          </a>
        </div>
      </li>
      <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
          <li>
            <a class="subheader">Name of university</a>
          </li>
          <li>
            <div class="divider"></div>
          </li>
          <!-- Programas -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" tabindex="0">
              <i class="material-icons no-padding">folder_open</i> Programas
            </a>
            <div class="collapsible-body">
              <ul>
                <li>
                  <a href="#">
                    <i class="material-icons no-padding">save</i>Crear
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="material-icons no-padding">list</i>Listar
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <!-- Convocatorias -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" tabindex="0">
              <i class="material-icons no-padding">folder_open</i> Convocatorias
            </a>
            <div class="collapsible-body">
              <ul>
                <li>
                  <a href="#">
                    <i class="material-icons no-padding">save</i>Crear
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="material-icons no-padding">list</i>Listar
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="material-icons no-padding">assignment_ind</i>Postulados
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <!-- Log out -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="material-icons">exit_to_app</i> Logout
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</header>

acce-better-edu/app/views/shared/_navbar_aprendiz.erb
<header>
  <div class="navbar-fixed">
    <nav class="">
      <div class="container nav-wrapper">
        <a href="<%= root_path %>" id="logo-st" class="brand-logo center">Access Better Education</a>
        <a href="<%= root_path %>" id="logo-nd" class="brand-logo center">ABE</a>
        <a href="#" data-target="mobile-demo" class="sidenav-trigger right"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li>
            <a rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="material-icons left">exit_to_app</i> Logout
            </a>
          </li>
        </ul>
      </div>
    </nav>
  </div>
  <div>
    <ul class="sidenav sidenav-fixed" id="mobile-demo">
      <li>
        <div class="user-view">
          <div class="background">
            <img src="https://materializecss.com/images/office.jpg">
          </div>
          <a href="#user"><img class="circle" src="https://materializecss.com/images/yuna.jpg"></a>
          <a href="#name"><span class="white-text name">Aprendiz</span></a>
          <a href="#email">
            <span class="white-text email">
              <%= current_user.email %>
            </span>
          </a>
        </div>
      </li>
      <li class="no-padding">
        <ul class="collapsible collapsible-accordion">
          <!-- Convocatorias -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" tabindex="0">
              <i class="material-icons no-padding">folder_open</i> Convocatorias
            </a>
            <div class="collapsible-body">
              <ul>
                <li>
                  <a href="#">
                    <i class="material-icons no-padding">list</i>Listar
                  </a>
                </li>
                <li>
                  <a href="#">
                    <i class="material-icons no-padding">assignment</i>Aplicaciones
                  </a>
                </li>
              </ul>
            </div>
          </li>
          <!-- Log out -->
          <li class="bold">
            <a class="collapsible-header waves-effect waves-teal" rel="nofollow" data-method="delete" href="/users/sign_out">
              <i class="material-icons">exit_to_app</i> Logout
            </a>
          </li>
        </ul>
      </li>
    </ul>
  </div>
</header>

acce-better-edu/app/views/shared/_navbar_login.html.erb
<header>
  <div class="navbar-fixed">
    <nav class="">
      <div class="container nav-wrapper">
        <a href="<%= root_path %>" id="logo-st" class="brand-logo center">Access Better Education</a>
        <a href="<%= root_path %>" id="logo-nd" class="brand-logo center">ABE</a>
        <ul id="nav-mobile" class="right">
          <li>
            <a href="<%= new_user_session_path %>">
              <i class="material-icons left">lock_open</i> Login
            </a>
          </li>
<!--          <li>
            <a href="<%#= new_user_registration_path %>">
              <i class="material-icons left">assignment_ind</i> Sign up
            </a>
          </li>-->
        </ul>
      </div>
    </nav>
  </div>
</header>