acce-better-edu/config/routes.rb
Rails.application.routes.draw do

  devise_for :users

  root 'dashboard#index'

  get 'dashboard/', to: 'dashboard#index'

  #Ruta para los formularios de la aplicación web
  resources :departamento

  resources :ciudad

  resources :universidad

  resources :rol

  resources :tipodocumento

  resources :persona

  #Ruta para api rest

  namespace :api do
    namespace :v1 do
      resources :departamento
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

acce-better-edu/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

acce-better-edu/app/models/ciudad.rb
class Ciudad < ApplicationRecord

  #Una Ciudad pertenece a un departamento
  belongs_to :departamento

  #Una Ciudad tiene muchas Universidades
  has_many :universidad

end

acce-better-edu/app/models/convocatorium.rb
class Convocatorium < ApplicationRecord

    belongs_to :programa
end

acce-better-edu/app/models/departamento.rb
class Departamento < ApplicationRecord

  #Un Departamento tiene muchas Ciudades o Municipios
  has_many :ciudad

end

acce-better-edu/app/models/permiso.rb
class Permiso < ApplicationRecord

    belongs_to :rol
end

acce-better-edu/app/models/persona.rb
class Persona < ApplicationRecord

    belongs_to :tipo_documento

    has_many :user

    has_many :persona_universidad
    has_many :universidad, through: :persona_universidad
end

acce-better-edu/app/models/persona_universidad.rb
class PersonaUniversidad < ApplicationRecord
end

acce-better-edu/app/models/programa.rb
class Programa < ApplicationRecord

    belongs_to :universidad

    has_many :convocatorium
end

acce-better-edu/app/models/rol.rb
class Rol < ApplicationRecord

    has_many :permiso
    has_many :user
end

acce-better-edu/app/models/tipo_documento.rb
class TipoDocumento < ApplicationRecord

    has_many :persona
end

acce-better-edu/app/models/universidad.rb
class Universidad < ApplicationRecord

  #Una Universidad pertenece a una Ciudad
  belongs_to :ciudad

  #Una Universidad tiene muchos programas
  has_many :programa

  has_many :persona_universidad
  has_many :persona, through: :persona_universidad

end

acce-better-edu/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  belongs_to :rol
  belongs_to :persona
end

acce-better-edu/app/controllers/persona_controller.rb
class PersonaController < ApplicationController

  before_action :authenticate_user!
  before_action :set_persona, only: [:edit, :update]

  def index
    @personas = Persona.all
  end

  def new
  end

  def create

  end

  def edit

  end

  def update

  end

  private
  def set_persona
    @persona = Persona.find(params[:id])
  end
end

acce-better-edu/app/controllers/rol_controller.rb
class RolController < ApplicationController

  before_action :authenticate_user!
  before_action :set_rol, only: [:edit, :update]

  def index
    @roles = Rol.all
  end

  def new
  end

  def create

    validar = Rol.find_by(nombre: request_params[:nombre])

    if validar.nil?

      rol = Rol.new(request_params)

      response = rol.save

      if response

        render json: {
            estado: 0,
            mensaje: "Success: El Rol fue creado correctamente"
        }
      else

        render json: {
            estado: 1,
            mensaje: "Error: No se pudo crear el rol"
        }
      end

    else
      render json: {
          estado: 1,
          mensaje: "Error: El rol ya existe descripción: " + validar.descripcion
      }
    end

  end

  def edit
  end

  def update

    response = @rol.update(request_params);

    if response

      render json: {
          estado: 0,
          mensaje: "Success: El rol fue actualizado correctamente"
      }
    else

      render json: {
          estado: 1,
          mensaje: "Error: No se pudo actualizar el rol"
      }
    end

  end

  private

  def set_rol
    @rol = Rol.find(params[:id])
  end

  def request_params
    params.require(:rol).permit(
        :nombre,
        :menu,
        :descripcion
    )
  end
end

acce-better-edu/app/helpers/application_helper.rb
module ApplicationHelper
end

acce-better-edu/app/helpers/ciudad_helper.rb
module CiudadHelper
end

acce-better-edu/app/helpers/convocatoria_helper.rb
module ConvocatoriaHelper
end

acce-better-edu/app/helpers/dashboard_helper.rb
module DashboardHelper
end

acce-better-edu/app/helpers/permiso_helper.rb
module PermisoHelper
end

acce-better-edu/app/helpers/persona_helper.rb
module PersonaHelper
end

acce-better-edu/app/helpers/programa_helper.rb
module ProgramaHelper
end

acce-better-edu/app/helpers/rol_helper.rb
module RolHelper
end

acce-better-edu/app/helpers/universidad_helper.rb
module UniversidadHelper
end

acce-better-edu/app/views/persona/edit.html.erb
<div class="center">
  <h4>Actualizar Persona</h4>
</div>
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div id="div-message" class="hidden-element">
      <span id="span-message" class="white-text"></span>
    </div>
    <div id="div-progress" class="progress hidden-element">
      <div class="indeterminate"></div>
    </div>
  </div>
</div>
<div class="row">
  <form id="frm-modificarPersona" class="col s12 m6 offset-m3">
    <div class="row">
      <div class="input-field col s12">
        <select name="select-tipoDocumento">
          <option value="" disabled selected>Seleccionar...</option>
          <% TipoDocumento.all.each do |td| %>
            <% if td.id == @persona.tipo_documento.id %>
            <option value="<%= td.id %>" selected><%= td.nombre %></option>
            <% else %>
            <option value="<%= td.id %>"><%= td.nombre %></option>
            <% end %>
          <% end %>
        </select>
        <label>Tipo Documento *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-documento" type="text" name="txt-documento" class="validate" value="<%= @persona.num_documento %>">
        <label for="txt-documento">Numero Documento *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-nombre" type="text" name="txt-nombre" class="validate" value="<%= @persona.nombre %>">
        <label for="txt-nombre">Nombre *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-priapellido" type="text" name="txt-priapellido" class="validate" value="<%= @persona.pri_apellido %>">
        <label for="txt-priapellido">Primer Apellido *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-segapellido" type="text" name="txt-segapellido" class="validate" value="<%= @persona.seg_apellido %>">
        <label for="txt-segapellido">Segundo Apellido *</label>
      </div>
      <div class="input-field col s12">
        <select name="select-genero">
          <option value="" disabled selected>Seleccionar...</option>
          <% if @persona.genero == "F" %>
          <option value="F" selected>Femenino</option>
          <option value="M">Masculino</option>
          <% elsif @persona.genero == "M" %>
          <option value="F" >Femenino</option>
          <option value="M" selected>Masculino</option>
          <% end %>
        </select>
        <label>Genero *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-fechanacimiento" type="text" name="txt-fechanacimiento" class="validate datepicker" value="<%= @persona.fecha_nacimiento %>">
        <label for="txt-fechanacimiento">Fecha Nacimiento *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-direccion" type="text" name="txt-direccion" class="validate" value="<%= @persona.direccion %>">
        <label for="txt-direccion">Direccion *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-telefono" type="text" name="txt-telefono" class="validate" value="<%= @persona.telefono %>">
        <label for="txt-telefono">Teléfono *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-celular" type="text" name="txt-celular" class="validate" value="<%= @persona.celular %>">
        <label for="txt-celular">Celular *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-email" type="text" name="txt-email" class="validate" value="<%= @persona.email %>">
        <label for="txt-email">Email *</label>
      </div>
    </div>
    <div class="row">
      <div class="col s6">
        <input type="hidden" name="txt-id" value="<%= @persona.id %>">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button type="button" class="btn" id="btn-modificarPersona" onclick="">
          Actualiza <i class="material-icons right">edit</i>
        </button>
      </div>
      <div class="col s6">
        <a href="<%= persona_index_path %>" class="btn">
          Listar <i class="material-icons right">list</i>
        </a>
      </div>
    </div>
  </form>
</div>

acce-better-edu/app/views/persona/index.html.erb
<div class="row">
  <div class="col s12 center">
    <h2>Persona</h2>
  </div>
</div>
<div class="row">
  <div class="col s12">
    <table class="highlight responsive-table">
      <thead>
      <tr>
        <th>Tipo Documento</th>
        <th>No. Documento</th>
        <th>Nombre</th>
        <th>Primer Apellido</th>
        <th>Segundo Apellido</th>
        <th>Genero</th>
        <th>Editar</th>
      </tr>
      </thead>
      <tbody>
      <% @personas.each do |per| %>
      <tr>
        <td><%= per.tipo_documento.nombre %></td>
        <td><%= per.num_documento %></td>
        <td><%= per.nombre %></td>
        <td><%= per.pri_apellido %></td>
        <td><%= per.seg_apellido %></td>
        <td><%= per.genero %></td>
        <td>
          <a href="<%= edit_persona_path(per.id) %>"><i class="material-icons">edit</i></a>
        </td>
      </tr>
      <% end %>
      </tbody>
    </table>
  </div>
</div>

acce-better-edu/app/views/persona/new.html.erb
<div class="center">
  <h4>Crear Persona</h4>
</div>
<div class="row">
  <div class="col s12 m6 offset-m3">
    <div id="div-message" class="hidden-element">
      <span id="span-message" class="white-text"></span>
    </div>
    <div id="div-progress" class="progress hidden-element">
      <div class="indeterminate"></div>
    </div>
  </div>
</div>
<div class="row">
  <form id="frm-crearPersona" class="col s12 m6 offset-m3">
    <div class="row">
      <div class="input-field col s12">
        <select name="select-tipoDocumento">
          <option value="" disabled selected>Seleccionar...</option>
          <% TipoDocumento.all.each do |td| %>
            <option value="<%= td.id %>"><%= td.nombre %></option>
          <% end %>
        </select>
        <label>Tipo Documento *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-documento" type="text" name="txt-documento" class="validate">
        <label for="txt-documento">Numero Documento *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-nombre" type="text" name="txt-nombre" class="validate">
        <label for="txt-nombre">Nombre *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-priapellido" type="text" name="txt-priapellido" class="validate">
        <label for="txt-priapellido">Primer Apellido *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-segapellido" type="text" name="txt-segapellido" class="validate">
        <label for="txt-segapellido">Segundo Apellido *</label>
      </div>
      <div class="input-field col s12">
        <select name="select-genero">
          <option value="" disabled selected>Seleccionar...</option>
          <option value="F">Femenino</option>
          <option value="M">Masculino</option>
        </select>
        <label>Genero *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-fechanacimiento" type="text" name="txt-fechanacimiento" class="validate datepicker">
        <label for="txt-fechanacimiento">Fecha Nacimiento *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-direccion" type="text" name="txt-direccion" class="validate">
        <label for="txt-direccion">Direccion *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-telefono" type="text" name="txt-telefono" class="validate">
        <label for="txt-telefono">Teléfono *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-celular" type="text" name="txt-celular" class="validate">
        <label for="txt-celular">Celular *</label>
      </div>
      <div class="input-field col s12">
        <input id="txt-email" type="text" name="txt-email" class="validate">
        <label for="txt-email">Email *</label>
      </div>
    </div>
    <div class="row">
      <div class="col s6">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
        <button type="button" class="btn" id="btn-crearPersona" onclick="">
          Crear <i class="material-icons right">save</i>
        </button>
      </div>
      <div class="col s6">
        <a href="<%= persona_index_path %>" class="btn">
          Listar <i class="material-icons right">list</i>
        </a>
      </div>
    </div>
  </form>
</div>